### ISSUE TITLE
Candl types not found

### ISSUE THREAD

**Issue by thiagotei** [periscop/candl#15]
Hi there,

I have one code developed using Candl that uses CandlOptions, CandlOptions, CandlDependence.
I could not find these types on my installation using the latest of this repo.
Have I installed the wrong version?

Thanks,

**Comment by ftynse** [comment]
That code must be more than 6 years old.  Names were changed in 79ceced9bda18435f6b841f037179a9ca0698b8d.  Use `candl_options_p` and `osl_dependence_p` instead.

**Comment by thiagotei** [comment]
Ok Thanks!
