### ISSUE TITLE
configure not checking for makeinfo

### ISSUE THREAD

**Issue by bondhugula** [periscop/candl#16]
Candl's configure isn't checking for texinfo, and as a result, there's a build time failure when texinfo isn't present. 

...
  MAKEINFO candl.info
/home/uday/git/pluto/candl/autoconf/missing: line 81: makeinfo: command not found
WARNING: 'makeinfo' is missing on your system.
         You should only need it if you modified a '.texi' file, or
         any other file indirectly affecting the aspect of the manual.
         You might want to install the Texinfo package:
         <https://www.gnu.org/software/texinfo/>
         The spurious makeinfo call might also be the consequence of
         using a buggy 'make' (AIX, DU, IRIX), in which case you might
         want to install GNU make:
         <https://www.gnu.org/software/make/>
make[4]: *** [Makefile:489: candl.info] Error 127
make[4]: Leaving directory '/home/uday/git/pluto/candl/doc'
make[3]: *** [Makefile:628: all-recursive] Error 1
make[3]: Leaving directory '/home/uday/git/pluto/candl/doc'
make[2]: *** [Makefile:905: all-recursive] Error 1
make[2]: Leaving directory '/home/uday/git/pluto/candl'
make[1]: *** [Makefile:519: all-recursive] Error 1
make[1]: Leaving directory '/home/uday/git/pluto'
make: *** [Makefile:391: all] Error 2
[uday@localhost pluto]$ sudo dnf -y install makeinfo
Last metadata expiration check: 0:54:47 ago on Thu 02 May 2019 11:56:24 PM IST.
No match for argument: makeinfo
Error: Unable to find a match

**Comment by bondhugula** [comment]
Adding the following in configure.ac should work:

AC_CHECK_PROG(TEXINFO, makeinfo, yes)
AS_IF([test x"$TEXINFO" != x"yes"], [AC_MSG_ERROR([Please install texinfo.])])

**Comment by harenome** [comment]
Added to `configure.ac` as suggested.
